Repository files-community/Website, pull requests merged in 2021-11, with the labels that each got.

#45 Files v2.0.33
  src/routes/blog/posts/introducing-files-v2-0-33.svx
Labels: approved

#50 Create new style for `<kbd>` tags in the docs.
  src/routes/docs/configuring/keyboard-shortcuts.svx
  src/styles/_markdown.scss
Labels: enhancement

#17 A bunch of small fixes
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/data/features.ts
  src/data/fetchHomepageData.ts
  src/layout/CommunitySection/CommunitySection.scss
  src/layout/DesignSection/DesignSection.scss
  src/layout/FeaturesSection/FeatureShowcase.scss
  src/layout/FeaturesSection/FeatureShowcase.svelte
  src/layout/Footer/Footer.scss
  src/layout/HeroSection/HeroSection.scss
  src/layout/HeroSection/HeroSection.svelte
  src/layout/Navbar/Navbar.scss
  src/layout/ThemesSection/ThemesSection.scss
  src/lib/BlogCard/BlogCard.scss
  src/lib/Button/Button.scss
  src/lib/ContentDialog/ContentDialog.scss
  src/lib/Contributor/Contributor.scss
  src/lib/FeatureCard/FeatureCard.scss
  src/lib/HeaderChip/HeaderChip.scss
  src/lib/HyperlinkButton/HyperlinkButton.scss
  src/lib/ListViewItem/ListViewItem.scss
  src/lib/MenuFlyout/MenuFlyout.scss
  src/lib/PageSection/PageSection.scss
  src/lib/TerminalCommand/TerminalCommand.scss
  src/lib/TextBox/TextBox.scss
  src/lib/Titlebar/Titlebar.scss
  src/lib/TreeView/TreeView.svelte
  src/routes/__layout.svelte
  src/styles/_global.scss
  src/styles/_markdown.scss
  src/styles/_mixins.scss
  src/styles/pages/blog.scss
  src/styles/pages/blogPost.scss
  src/styles/pages/docs.scss
  src/styles/pages/error.scss
  tsconfig.json
Labels: enhancement

#51 Added cssnano
  package.json
  pnpm-lock.yaml
  src/lib/PageSection/PageSection.svelte
  svelte.config.js
Labels: enhancement

#55 Fixed all typescript errors (as indicated by svelte-check)
  pnpm-lock.yaml
  src/data/fetchHomepageData.ts
  src/layout/CommunitySection/CommunitySection.svelte
  src/layout/FeaturesSection/FeatureShowcase.svelte
  src/layout/HeroSection/HeroSection.svelte
  src/layout/Navbar/Navbar.svelte
  src/layout/ThemesSection/ThemesSection.svelte
  src/lib/MenuFlyout/MenuFlyoutWrapper.svelte
  src/lib/TreeView/TreeView.svelte
  src/lib/tilt.ts
  src/routes/blog/posts/[slug].json.ts
  src/routes/blog/posts/__layout.svelte
  src/routes/docs/__layout.svelte
  src/routes/index.svelte
  src/styles/pages/blog.scss
Labels: enhancement

#64 Added sideloading (stable and preview) download sources
  package.json
  pnpm-lock.yaml
  src/data/fetchHomepageData.ts
  src/data/links.ts
  src/layout/HeroSection/HeroSection.svelte
  src/lib/Metadata.svelte
  src/lib/ProgressRing/ProgressRing.scss
  src/lib/ProgressRing/ProgressRing.svelte
  src/lib/index.ts
  src/routes/download/__layout.svelte
  src/routes/download/preview.svelte
  src/routes/download/stable.svelte
  src/styles/_global.scss
Labels: enhancement

#66 Improve parallax performance with `requestAnimationFrame()`.
  src/layout/DesignSection/DesignSection.svelte
  src/routes/blog/index.svelte
Labels: enhancement

#69 Overhauled the `filterPages` function to include comments, types, etc.
  package.json
  pnpm-lock.yaml
  src/routes/docs/__layout.svelte
Labels: enhancement

#56 Fixed images outside figures in markdown.
  src/layout/Navbar/Navbar.svelte
  src/layout/ThemesSection/ThemesSection.scss
  src/styles/_markdown.scss
  src/styles/pages/blog.scss
Labels: enhancement, docs

#68 Fixed an issue with the download button not working correctly.
  src/layout/HeroSection/HeroSection.svelte
  src/routes/download/preview.svelte
  src/routes/download/stable.svelte
  static/branding/banner-download-dark.png
  static/branding/banner-download-light.png
Labels: approved, enhancement
