Repository files-community/Website, pull requests merged in 2022-12, with the labels that each got.

#288 Update item labels in navbar
  src/layout/Footer/Footer.svelte
  src/routes/+layout.svelte
Labels: enhancement

#298 Added a new download page
  package.json
  pnpm-lock.yaml
  src/app.html
  src/layout/DesignSection/DesignSection.scss
  src/layout/DesignSection/DesignSection.svelte
  src/layout/HeroSection/HeroSection.scss
  src/layout/HeroSection/HeroSection.svelte
  src/layout/index.ts
  src/routes/+page.svelte
  src/routes/docs/+layout.server.ts
  src/routes/download/+layout.svelte
  src/routes/download/+page.svelte
  src/routes/download/DownloadSourceCard.svelte
  src/routes/download/preview/+page.svelte
  src/routes/download/preview/+page.ts
  src/routes/download/stable/+page.svelte
  src/routes/download/stable/+page.ts
  src/routes/download/types.ts
  static/download-sources/msstore_dark.svg
  static/download-sources/msstore_light.svg
  static/download-sources/preview_dark.svg
  static/download-sources/preview_light.svg
Labels: enhancement

#300 Fix the `currentPage` searching
  package.json
  pnpm-lock.yaml
  src/routes/docs/+layout.server.ts
  src/routes/docs/+layout.svelte
Labels: bug

#303 Fix wrong Microsoft Store Icon theme mapping
  static/download-sources/msstore_dark.svg
  static/download-sources/msstore_light.svg
Labels: approved

#301 Added an RSS feed (`/blog/feed.rss`)
  package.json
  pnpm-lock.yaml
  src/routes/blog/feed.rss/+server.ts
  src/routes/blog/posts/+layout.svelte
  src/routes/blog/posts/+layout.ts
  src/styles/pages/blogPost.scss
Labels: enhancement

#310 Update building instructions for Files
  src/routes/docs/contributing/building-from-source/+page.md
Labels: approved

#313 Blog: 2.4 announcement
  src/routes/blog/posts/introducing-files-v2-4/+page.md
  static/blog-resources/filesv2-4/CreateArchive.png
  static/blog-resources/filesv2-4/ExtractArchive.png
  static/blog-resources/filesv2-4/MicaAlt.png
  static/blog-resources/filesv2-4/RoundCorners.png
  static/blog-resources/filesv2-4/StorageInformation.png
Labels: approved
