Repository files-community/Website, pull requests merged in 2022-01, with the labels that each got.

#46 Added playback hotkey in media preview to keyboard shortcuts documentation
  src/routes/docs/configuring/keyboard-shortcuts.svx
Labels: approved

#91 Updated documentation on setting Files as the default file manager
  src/data/docs.ts
  src/routes/docs/configuring/configure-win-e.svx
  src/routes/docs/configuring/replace-file-explorer.svx
  static/docs-resources/Settings-Dialog-Experimental.png
Labels: needs review

#73 Fix over scroll of navigation view items of docs page
  src/lib/TreeView/TreeView.svelte
  src/routes/docs/__layout.svelte
Labels: approved

#93 Update building-from-source.svx
  src/routes/docs/contributing/building-from-source.svx
Labels: approved

#89 Create introducing-files-v2-1.svx
  src/routes/blog/posts/introducing-files-v2-1.svx
  static/blog-resources/filesv2-1/HeroImage.jpg
  static/blog-resources/filesv2-1/PropertiesDialog.jpg
Labels: approved

#96 Fixed typo in blog post
  src/routes/blog/posts/introducing-files-v2-1.svx
Labels: needs review

#77 Updated code style
  src/routes/docs/contributing/code-style.svx
Labels: approved

#122 Fix eye icon
  src/data/features.ts
Labels: bug

#129 Fix file extension on docs edit button
  src/routes/docs/__layout.svelte
Labels: approved, bug

#131 Fixed SvelteKit config.
  package.json
  pnpm-lock.yaml
  svelte.config.js
Labels: bug
