Repository files-community/Website, pull requests merged in 2023-01, with the labels that each got.

#315 Feature: Localization with Crowdin
  .vscode/settings.json
  crowdin.yml
  package.json
  pnpm-lock.yaml
  src/app.html
  src/data/features.ts
  src/hooks.server.ts
  src/i18n/index.ts
  src/i18n/locales/en.json
  src/i18n/locales/he-IL.json
  src/layout/CommunitySection/CommunitySection.svelte
  src/layout/DesignSection/DesignSection.svelte
  src/layout/FeaturesSection/FeaturesSection.svelte
  src/layout/Footer/Footer.svelte
  src/layout/Navbar/Navbar.svelte
  src/layout/ThemesSection/ThemesSection.svelte
  src/lib/BlogCard/BlogCard.svelte
  src/lib/Contributor/Contributor.svelte
  src/lib/FeatureCard/FeatureCard.svelte
  src/lib/Metadata.svelte
  src/routes/+layout.svelte
  src/routes/+layout.ts
  src/routes/+page.svelte
  src/routes/blog/+page.svelte
  src/routes/docs/+layout.svelte
  src/styles/_global.scss
  static/fonts/OpenSans-italic.var.woff2
  static/fonts/OpenSans-roman.var.woff2
  svelte.config.js
  tsconfig.json
Labels: enhancement

#329 Update README with Crowding links
  README.md
  package.json
  pnpm-lock.yaml
Labels: enhancement

#343 Moved docs tree generation into docsTree.ts
  package.json
  pnpm-lock.yaml
  src/data/docsTree.ts
  src/routes/+layout.svelte
  src/routes/+layout.ts
  src/routes/docs/+layout.server.ts
Labels: approved

#348 finally fixed that annoying layout issue
  src/hooks.server.ts
  src/routes/+error.svelte
  src/routes/docs/+layout.svelte
  src/routes/download/+page.svelte
  src/styles/_global.scss
  src/styles/pages/blogPost.scss
  src/styles/pages/docs.scss
  src/styles/pages/error.scss
Labels: bug
