Repository files-community/Website, pull requests merged in 2023-06, with the labels that each got.

#442 statically build the locales object from the locale files
  package.json
  pnpm-lock.yaml
  src/i18n/index.ts
Labels: approved

#444 Docs: Update themes
  src/routes/docs/configuring/custom-themes/+page.md
Labels: approved

#447 re-enabled dependabot since it now supports pnpm
  .github/dependabot.yml
Labels: enhancement, dependencies

#457 Blog posts are now hidden before their set publish date
  src/routes/blog/+page.server.ts
Labels: enhancement

#455 Simplified the code for the features section
  package.json
  pnpm-lock.yaml
  src/layout/FeaturesSection/FeatureShowcase.scss
  src/layout/FeaturesSection/FeatureShowcase.svelte
  src/layout/FeaturesSection/FeaturesSection.scss
  src/layout/FeaturesSection/FeaturesSection.svelte
  src/layout/FeaturesSection/cloud/CloudShowcase.scss
  src/layout/FeaturesSection/cloud/CloudShowcase.svelte
  src/layout/FeaturesSection/preview/PreviewShowcase.scss
  src/layout/FeaturesSection/preview/PreviewShowcase.svelte
  src/layout/FeaturesSection/tabs/TabsShowcase.scss
  src/layout/FeaturesSection/tabs/TabsShowcase.svelte
  src/layout/FeaturesSection/tags/TagsShowcase.scss
  src/layout/FeaturesSection/tags/TagsShowcase.svelte
  src/lib/FeatureCard/FeatureCard.scss
  src/lib/FeatureCard/FeatureCard.svelte
Labels: enhancement

#462 Feature: Added the description of blog posts to their meta tags
  src/routes/blog/posts/+layout.svelte
Labels: enhancement

#464 i may or may have not misspelled "package"
  .github/dependabot.yml
Labels: bug

#466 Add og:description meta tag to blog posts
  src/routes/blog/posts/+layout.svelte
Labels: bug

#480 fixed the meta description for blogs, again
  package.json
  pnpm-lock.yaml
  src/i18n/locales/en.json
  src/lib/Metadata.svelte
  src/routes/+layout.svelte
  src/routes/blog/posts/+layout.svelte
Labels: bug
